### ISSUE TITLE
Some application goes full transparent and some goes full dark while using titlebar opacity less than 255

### ISSUE THREAD

**Issue by sowrensen** [Luwx/Lightly#10]
I set a titlebar opacity of 224 in the color-scheme. So far I found this issue with SM Player and VirtualBox.

**SM Player**
![background-missing](https://user-images.githubusercontent.com/13097375/91632028-e0764100-e9ff-11ea-8fe3-570767f977bc.png)

**VirtualBox**
![Screenshot_20200829_135219](https://user-images.githubusercontent.com/13097375/91632067-20d5bf00-ea00-11ea-94b3-ee6f962f2535.png)

To be confirmed that this is a Lightly issue rather than color-scheme, _I tried the same color-scheme with Breeze and Kvantum styles and both work fine_. However, VLC media player also shows no problem.

**Comment by Luwx** [comment]
Some applications don't support any kind of transparency. 

Add this line to lightlyrc (located in ~/.config), bellow [style] section: ```OpaqueApps=kscreenlocker,wine,vlc,virtualbox,smplayer``` 

If any other application show a similar problem, it's better to add it to the opaque list.
