### ISSUE TITLE
Totally black window when opening Oracle's Virtualbox

### ISSUE THREAD

**Issue by ryu-ketsueki** [Luwx/Lightly#100]
Virtualbox doesn't know how to handle Lightly. It displays a totally black screen until you select another Widget Style and reopen Virtualbox
![image](https://user-images.githubusercontent.com/39316730/115098590-381dda00-9f07-11eb-9169-6747458e17d1.png)
Also, the transparent titlebar without blur is also a bug but I don't know if this is Kwin's fault or Lightly. I checked the .json and it is saying the titlebar is to be blurred alright but it's not getting blurred.

**Comment by Luwx** [comment]
IIRC this was due to virtualbox not handling transparency. Since it is forced to be opaque now this should not happen.
