### ISSUE TITLE
Cannot Compile

### ISSUE THREAD

**Issue by G3NSVRV** [Luwx/Lightly#104]
```
CMake Error at CMakeLists.txt:12 (find_package):
  Could not find a configuration file for package "ECM" that is compatible
  with requested version "5.66.0".

  The following configuration files were considered but not accepted:

    /usr/share/ECM/cmake/ECMConfig.cmake, version: 5.54.0

-- Configuring incomplete, errors occurred!
See also "/home/g3nsvrv/Lightly/build/CMakeFiles/CMakeOutput.log".
```
[CMakeOutput.log](https://github.com/Luwx/Lightly/files/6402121/CMakeOutput.log)

I have an old Deepin 15 distro that on base was Debian 8 and was converted into Debian 10.
gcc --version shows that im using debian 8, do I need to change that? is that the default from debian 10?

**Comment by hberbary** [comment]
I've the same problem on Debian 10.
