### ISSUE TITLE
KWindowShadow: no such file or directory

### ISSUE THREAD

**Issue by DEV-ONI** [Luwx/Lightly#116]
Received an error on 'make' that states

`fatal error: KWindowShadow: No such file or directory`
 
I'm running KDE Plasma Version 5.12.9 with Qt version 5.9.5 if that helps
Am I missing something that needs to be updated? It seems I need to update my kwindowsystem?

**Comment by D3SOX** [comment]
Duplicate of #113 #83 #31

**Comment by DEV-ONI** [comment]
Thank you for the response.
A requirements section would be appreciated.
