### ISSUE TITLE
Some applications are completely black after setting application style to lightly 

### ISSUE THREAD

**Issue by Da-Viper** [Luwx/Lightly#12]
**Scenario :** Opening virtual box 

**Observed Result** 
The application is completely black or some some area is black.

**Expected result** : 
the application is painted correctly without any black areas.

here is a picture of obs when using lightly 
![obs](https://user-images.githubusercontent.com/57949090/92274409-18402580-eee5-11ea-829d-fc326f75f996.png)

here is a short video showing what i mean 

https://streamable.com/pqtdle

**Comment by sowrensen** [comment]
It is already addressed. See here #10.
