### ISSUE TITLE
LibreOffice tabbed user interface needs a touch maybe?

### ISSUE THREAD

**Issue by Sadi58** [Luwx/Lightly#120]
Thank you so much for this superb work which I've discovered just today.
I think LibreOffice tabbed user interface might look much better without that darker grey background - at least it shouldn't go past the top border.
![Screenshot_2021-07-26-19-12-44](https://user-images.githubusercontent.com/6375934/127029215-64ac921a-f078-41bb-baf3-4ff0324e52c9.png)

**Comment by Luwx** [comment]
LibreOffice is a mess, style-wise. 

I did some refactoring in the tab code that I'll push soon, that maybe fix the light grey background.

**Comment by Sadi58** [comment]
Thank you.
Yes, unfortunately LibreOffice and some others like Firefox always have theming issues in Linux.

**Comment by Sadi58** [comment]
Actually, it seems tab background in general might benefit from a little polish.
For instance, it doesn't look very well in Dolphin either (a little white area to the left and a large one to the right, and underneath round corners), although it is OK in Kate as seen in the screenshot below.
Maybe it's better not to set a different tab background and display tabs with those thin light grey borders and a little shadow only?
![Screenshot_2021-07-28-14-02-40](https://user-images.githubusercontent.com/6375934/127313474-df2ef531-d532-42ff-97d2-e439993a1b96.jpg)

**Comment by Sadi58** [comment]
Also, I've just noticed that the area between tabs and folder contents in Dolphin not only seems an unnecessary duplication but the thin light grey border at the bottom sometimes disappears while switching between several tabs. And I have no idea if this can be fixed in the theme or Dolphin.

**Comment by doncsugar** [comment]
@Sadi58 Does the round corner on the `usr` tab appear when using other themes (like a similarly rounded Kvantum theme)?

**Comment by Sadi58** [comment]
@doncsugar Here's a screenshot from the WhiteSur theme. But I think it has some issues with round corners already, sometimes displaying dark corners behind round corners of main window as similar to this screenshot, which goes away after hovering or clicking the window.
![20210915-110039_Screenshot](https://user-images.githubusercontent.com/6375934/133396499-3b68261e-a658-49fc-9052-9e7e30c2611c.jpg)

**Comment by doncsugar** [comment]
I think with this it seems that it is a Dolphin problem.

I'm not sure, but you might want to look into graphics driver issues if the theme's blurred area is turning black.

**Comment by Sadi58** [comment]
@doncsugar Lightly round corners don't have this problem, so I think WhiteSur theme needs a fix for this.
Lightly has an issue only in LO tabbed user interface and Dolphin tabs.

**Comment by Luwx** [comment]
This should be a little better right now. The issues in dolphin cannot be solvable unless I implement a different style.
