### ISSUE TITLE
Compatibility with Window Buttons widget

### ISSUE THREAD

**Issue by Sadi58** [Luwx/Lightly#124]
**Window Buttons** applet (https://github.com/psifidotos/applet-window-buttons) is great for maximized windows. However, it requires a `MonochromeIconsPrefix=`  value in the aurorae theme config file (`*` if the button images are good for monochrome, or something like `monochrome-` if we need different ones for that purpose) if the user has a **Latte Dock** panel/dock with **Smart** color setting.

Apparently nothing is added to `~/.local/share/aurorae/themes` after the installation of **Lightly**.
I wonder how this can be handled - e.g. where can I find the **Window Decorations** (aurorae) config file?

**Comment by Luwx** [comment]
Since Lightly decoration is not an aurorae theme it doesn't an aurorae theme config. It should work out of the box.
