### ISSUE TITLE
Transparent toolbar on Kirigami

### ISSUE THREAD

**Issue by ryu-ketsueki** [Luwx/Lightly#128]
Lightly has the transparent toolbars on kxmlgui but they could be added to Kirigami as well for sake of consistency. So far it is like this
![image](https://user-images.githubusercontent.com/39316730/131228259-24185afa-ed35-4a17-b901-7c5b7f0c95ce.png)

**Comment by Rmdhn1** [comment]
how did you get menubar transparency? i can't find it

**Comment by Rmdhn1** [comment]
so i managed to get the tool and menubar transparent on dolhpin but the titlebar is still opaque

**Comment by Luwx** [comment]
Not possible :/
