### ISSUE TITLE
Changing title bar icon

### ISSUE THREAD

**Issue by WahidIslamLinad** [Luwx/Lightly#131]
My questions might be kinda dumb but I'm new to linux..but I was trying to change the default title bar icon of lightly..couldn't find any solutions by searching so is there any way to do these?

**Comment by yusi1** [comment]
Go to System Settings -> Appearance -> Window Decorations 
Then you can change the title bar theme

**Comment by WahidIslamLinad** [comment]
> Go to System Settings -> Appearance -> Window Decorations then you can change the title bar theme there.

I can could change the window decorations but i really like the lightly/ breeze decorator..but only the icons are bugging me that's why i wanned to change the icons only..

**Comment by Luwx** [comment]
If by icon you mean the button icon then there is no way to change them.
