### ISSUE TITLE
window outline doesn't work all the time and right click menu/hamburger menu is too big.

### ISSUE THREAD

**Issue by AtifChy** [Luwx/Lightly#14]
![Screenshot_20200911_154918](https://user-images.githubusercontent.com/42291930/92909460-f3016900-f448-11ea-8678-ffc1bc7be93e.png)
hamburger menu is too big. Also window outline doesn't work on all apps.

**Comment by Luwx** [comment]
Is the option "round bottom corners" enabled? The outline won't appear in windows that don't have round corners. And yes, it doesn't work on all windows. Maybe implementing Kwin effect is better for this.

About the menu, that hamburger menu has way too many entries, and that's not something the style can control.

**Comment by AtifChy** [comment]
until it gets fixed. You can add a option to disable outline completely?

**Comment by Luwx** [comment]
Sure :)

**Comment by Luwx** [comment]
The outine and round corners feature are now implemented through a kwin effect: https://github.com/Luwx/LightlyShaders
