### ISSUE TITLE
Can't apply on KDE Plasma 5.22.5 (KF 5.87.0)

### ISSUE THREAD

**Issue by elegos** [Luwx/Lightly#140]
Hello!

I've installed the upcoming Fedora 35 with KDE Plasma 5.22.5 and KDE DFramework 5.87.0.
I've compiled Lightly as usual, but I face two problems:

1. The style preview is broken
2. When I try to apply it nonetheless, an error shows (which, translated, is more or less: "Impossible to apply the selected style <<Lightly>>")

![immagine](https://user-images.githubusercontent.com/577975/137649251-50ccb51d-4adf-4eda-8fd7-c027caa7dfbf.png)

Is there anything I can do to help you debug this?

Thanks, and thanks for the awesome style!

**Comment by Luwx** [comment]
Looks like a issue with the fedora packaging. Feel free to reopen if you are still facing the problem.

**Comment by pizzadude** [comment]
i had the same issue, i fixed it by building an RPM instead of building via "sudo make install"
