### ISSUE TITLE
Konsole menu bar transparent without blur

### ISSUE THREAD

**Issue by ezedksl** [Luwx/Lightly#141]
``
![Screenshot_20211027_000515](https://user-images.githubusercontent.com/70861611/138993055-6c251484-a64f-43a9-86c8-32d0162cfa7a.png)

**Comment by Rmdhn1** [comment]
how did you achieve the menu bar transparency in the firstplace? also try force blur

**Comment by Rmdhn1** [comment]
i already set the menu slider to transparent

**Comment by Luwx** [comment]
Lightly blur is incompatible with konsole, so you have to enable the blur in the konsole color scheme.
