### ISSUE TITLE
Installation on Lubuntu

### ISSUE THREAD

**Issue by Onanceme** [Luwx/Lightly#145]
When installing it on Lubuntu it gives me this issue

`CMake Error at CMakeLists.txt:12 (find_package):
  Could not find a configuration file for package "ECM" that is compatible
  with requested version "5.78.0".

  The following configuration files were considered but not accepted:

    /usr/share/ECM/cmake/ECMConfig.cmake, version: 5.68.0

-- Configuring incomplete, errors occurred!
See also "/home/user/Downloads/Lightly/build/CMakeFiles/CMakeOutput.log"`

**Comment by GustavoRFS** [comment]
Same here in Kubuntu :(

**Comment by base2code** [comment]
I had the same error in Lubuntu and solved it by changing the version:

File CMakeLists.txt in root:
Changed
`set(KF5_MIN_VERSION "5.78.0")`
to
`set(KF5_MIN_VERSION "5.68.0")`

**Comment by Luwx** [comment]
That's a very old version of KDE Frameworks. Your system should have a more recent version.
