### ISSUE TITLE
The dependencies broke the system

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [Luwx/Lightly#15]
Hi, when I used:
`
sudo apt install build-essential libkf5config-dev libkdecorations2-dev libqt5x11extras5-dev qtdeclarative5-dev extra-cmake-modules libkf5guiaddons-dev libkf5configwidgets-dev libkf5windowsystem-dev libkf5coreaddons-dev gettext`

The system (KDE neon) broke, I needed to reinstall many things. Maybe there are some conflicts there.

**Comment by Luwx** [comment]
Installing a package broke your system? damn.. What exactly broke?

Unfortunately I don't use any Debian based distro, and I don't know what's wrong with those packages. I'll leave this open in case someone knows.

**Comment by ViniciusBRodrigues** [comment]
Yeah... there was some problem in plasma, I don't know exactly where but even SDDM was broken. Unfortunately I didn't pay attention in the installation, once seems to be ok with the dependencies.

But I tried install the dependencies again and seems to be nothing wrong, it was a very strange behavior. Currently, only gettext and libcroco3 are out of my system.

**Comment by Luwx** [comment]
Just installed on neon and it went fine. Must be an isolated case then.
