### ISSUE TITLE
The bar show Space Information in Dolphin became a blurred box

### ISSUE THREAD

**Issue by vuongtuha** [Luwx/Lightly#150]
I tried to reset config in Application Style to default, but this ugly box still appears. Hope anyone guides me re-config
![Screenshot_20220114_095029](https://user-images.githubusercontent.com/70053986/149445213-678d8ada-ae32-42cd-bc4d-08d49cfba967.png)

**Comment by Cognitohazard** [comment]
Have this problem too.

**Comment by nisiddharth** [comment]
This is same as #69

**Comment by Luwx** [comment]
Duplicate of https://github.com/Luwx/Lightly/issues/69
