### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by aliquo93** [Luwx/Lightly#158]
I think this is the best KDE theme ever made, I hope it hasn't been discontinued.

**Comment by Nick-Shadow** [comment]
The main contributor seems to wait a while between pushes. https://github.com/Luwx Look at the commit frequency here. That being said I totally agree about the former statement.

**Comment by Luwx** [comment]
I have been really out of time and motivation lately to continue work on this project. It isn't dead, but probably there will not be new features.

**Comment by ChrTall** [comment]
@Luwx 
Are you in contact with KDE Devs? Maybe they would consider investing in this project, because it looks way better than Breeze.

**Comment by AlphaCraft9658** [comment]
> @Luwx 
> Are you in contact with KDE Devs? Maybe they would consider investing in this project, because it looks way better than Breeze.

Actually a good suggestion.

**Comment by kynadev** [comment]
I know there is a team working on Ocean (next era of breeze, similar ish to this, I am sure they are aware of this but perhaps communicating with them could help them out? And it would not be as much work as continuing on your own.
