### ISSUE TITLE
Issues with Cmake (Linux Mint 20.3)

### ISSUE THREAD

**Issue by Alium-Realis** [Luwx/Lightly#159]
So I happen to have problems with building the repository, as when I use the "_cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF .._"  command, it outputs the error below, not allowing me to install the theme:

CMake Error at CMakeLists.txt:12 (find_package):
  Could not find a configuration file for package "ECM" that is compatible
  with requested version "5.78.0".

  The following configuration files were considered but not accepted:

    /usr/share/ECM/cmake/ECMConfig.cmake, version: 5.68.0

-- Configuring incomplete, errors occurred!
See also "/home/morgan/Downloads/Lightly/build/CMakeFiles/CMakeOutput.log".

Any help will be much appreciated :)

**Comment by souzadevinicius** [comment]
https://github.com/Luwx/Lightly/issues/145
