### ISSUE TITLE
Display scaling issues

### ISSUE THREAD

**Issue by LegendaryMauricius** [Luwx/Lightly#16]
Transparent lines randomly appear around ui elements on mouse hover, when using non-integer global scale. The lines disappear when resizing the window.
Also, the window borders aren't aligned with titlebar borders when scaling and show up in maximized mode, while the titlebar borders do disappear when maximized.

**Comment by Luwx** [comment]
Can you send a screenshot?

**Comment by LegendaryMauricius** [comment]
![Screenshot_20200912_042808](https://user-images.githubusercontent.com/62662583/92985195-b23d3a80-f4b0-11ea-98ce-8a8563d2b69f.png)
![Screenshot_20200912_043340](https://user-images.githubusercontent.com/62662583/92985264-52935f00-f4b1-11ea-9ca7-09f546cc5aaf.png)
They are a bit hard to catch when screenshooting since they disappear when the focus is changed or any animation is triggered, but they are quite noticeable when hovering with cursor or zooming out.

**Comment by Luwx** [comment]
Ok, I can reproduce it. Looks Kvantum has the same problem https://github.com/tsujan/Kvantum/issues/546

For now, you have to disable any transparency in the window, for this go to lightly style settings and unckeck "round bottom corners", and set the sidebar opacity to 100%.
