### ISSUE TITLE
Weird graphical glitches in Wayland

### ISSUE THREAD

**Issue by ryu-ketsueki** [Luwx/Lightly#161]
Whenever I right click on the titlebar of any window on the Wayland session, it displays some weird graphical glitches in the list highlights and the blur effect does not work. This does not happen in X11, as far as I could test. Only Wayland. Regular context menus also behave as expected. Only when right clicking a window's titlebar is when this happens.

**Comment by aleasto** [comment]
nvidia gpu?

**Comment by ryu-ketsueki** [comment]
No, it's Intel.

**Comment by aleasto** [comment]
Ok, cause i thought this was an issue with my nvidia card.

**Comment by ryu-ketsueki** [comment]
![Flameshot_20220318_215039](https://user-images.githubusercontent.com/39316730/159191412-4432ad28-05a9-4045-af55-9b7b00f4f10a.png)
This is the last one I managed to capture. There is also selection persistance but is hard to get it on screen with a screenshot tool

**Comment by Luwx** [comment]
Most likely a driver & Kwin related issue. Does it happen only with Lightly?

**Comment by ryu-ketsueki** [comment]
I noticed it happened with regular Breeze too so it's an upstream problem. I'll close with a comment and hope it gets fixed on their side. I submitted a bug report over there
