### ISSUE TITLE
Lightly and the Korners fix in upcoming plasma 5.25? 

### ISSUE THREAD

**Issue by RussH** [Luwx/Lightly#167]
Hi just a question (apologies, don't know if you guys hang out in IRC / Matrix someplace). Is Lightly going to take advantage of the Korners fix that seems to be poised to be deployed in Plasma 5.25? https://invent.kde.org/plasma/kwin/-/merge_requests/1961

I see from the commit info that there has to be some masking in themes to allow it to operate correctly.

**Comment by Luwx** [comment]
Yes I'll update the decoration once 5.25 is released, the fix is really simple to implement.
