### ISSUE TITLE
Delete button is oversized

### ISSUE THREAD

**Issue by codic12** [Luwx/Lightly#2]
From the search field in KDE's system settings.

Lightly:
![image](https://user-images.githubusercontent.com/48339289/89202034-3a9df680-d567-11ea-8ef1-38b7be55338a.png)
Breeze:
![image](https://user-images.githubusercontent.com/48339289/89202064-44bff500-d567-11ea-89ce-5f68efd3ff33.png)

**Comment by Luwx** [comment]
Yeah, some QML items in system settings are not respecting borders.

**Comment by Luwx** [comment]
This is a bug in kirigami, not related to Lightly.
