### ISSUE TITLE
Context menu of "add panel"-option is not blurred

### ISSUE THREAD

**Issue by nnamliehbes** [Luwx/Lightly#20]
First off I want to compliment you on your theme!

In the latest update (v0.3-alpha) I've noticed a small bug(?) and I don't know if you've also encountered this. As you can see in the screenshot attached below, the context menu of the "add panel"-option ("Kontrolleiste hinzufügen" in German) isn't blurred. 

![Lightly_Bug](https://user-images.githubusercontent.com/63071633/93000662-2962e500-f52a-11ea-9ea0-4d9a6235c153.png)

**Comment by Luwx** [comment]
I had the same problem when I rebooted my laptop, and it went away after restarting plasmashell. Can you test if this issue persists after restarting plasma with ```pkill plasmashell && kstart5 plasmashell```?

**Comment by sowrensen** [comment]
> I had the same problem when I rebooted my laptop, and it went away after restarting plasmashell. Can you test if this issue persists after restarting plasma with `pkill plasmashell && kstart5 plasmashell`?

Yes. It goes away if you restart plasmashell. Actually I have an alias set for the command `killall plasmashell && kstart5 plasmashell`. 😛

**Comment by nnamliehbes** [comment]
> I had the same problem when I rebooted my laptop, and it went away after restarting plasmashell. Can you test if this issue persists after restarting plasma with `pkill plasmashell && kstart5 plasmashell`?

Yes, it went away after restarting plasmashell with `pkill plasmashell && kstart5 plasmashell`, thanks for your help! Unfortunately it comes back after every reboot, but that is okay :D

**Comment by Luwx** [comment]
I think this is fixed now.
