### ISSUE TITLE
[Feature Request] QT6 support

### ISSUE THREAD

**Issue by alba4k** [Luwx/Lightly#200]
is there any likelyhood of this supporting QT6 in the near future, e.g. using qt6ct, where it currently doesnt even show up (unlike qt5ct, which works as expected)?

**Comment by boehs** [comment]
I'm not looking forward to it but I'm probably going to end up porting it on my fork after 5.27

**Comment by alba4k** [comment]
@boehs that sounds great

in case it's not merged with the mainline, I could maintain a separate aur package `lightly-qt6-git` or smth if you'd like, since a lot of people would find that helpful

**Comment by boehs** [comment]
> @boehs that sounds great
> 
> in case it's not merged with the mainline, I could maintain a separate aur package `lightly-qt6-git` or smth if you'd like, since a lot of people would find that helpful

I am working on gaining permissions on this repository, or if that fails, the AUR package

**Comment by alba4k** [comment]
However it goes, let me know how this ends :)

**Comment by AndhikaWB** [comment]
@Luwx just made some commits in another repository not too long ago. Wonder why he didn't make any statement regarding the continuity of this project, or at least giving some contributors greater access to manage this repository.

**Comment by alba4k** [comment]
Yeah, exactly like there are multiple pull requests just fixing typos in README.md that got no answer

**Comment by vollowx** [comment]
QT6 and qt6ct are already out for months, but the author still didn't do anything, could you please make a QT6 version of lightly?

**Comment by alba4k** [comment]
Maybe @boehs has made some progress?

**Comment by Kara-Zor-El** [comment]
I am not a C++ developer nor a QT developer but I have been tinkering around in the source code in my free time. I have a version of it that isn't compiling yet but I could publish it to my GitHub if anyone wants to try helping me out with it?

**Comment by vollowx** [comment]
> I am not a C++ developer nor a QT developer but I have been tinkering around in the source code in my free time. I have a version of it that isn't compiling yet but I could publish it to my GitHub if anyone wants to try helping me out with it?

Sure, there will always be persons that need QT6 version of this and glad to help.

**Comment by Kara-Zor-El** [comment]
@volpan here it is. I am now like 75% of the way there(ish) on my hacky version of doing so (without X11 support as well because idk why X11Extras dont work on my system)
https://github.com/Kara-Zor-El/Lightly

**Comment by edpil02** [comment]
I finally succeeded  to make  a  hacky build  with  Qt6 and  KF6  but  without  X11  (no  X11Extras in Qt6)
 
Requires: cmake-filesystem(x86-64) libKF6ColorScheme.so.6()(64bit) libKF6ConfigCore.so.6()(64bit) libKF6ConfigGui.so.6()(64bit) libKF6CoreAddons.so.6()(64bit) libKF6GuiAddons.so.6()(64bit) libKF6I18n.so.6()(64bit) libKF6IconThemes.so.6()(64bit) libKF6KCMUtils.so.6()(64bit) libKF6KCMUtilsCore.so.6()(64bit) libKF6Style.so.6()(64bit) libKF6WidgetsAddons.so.6()(64bit) libKF6WindowSystem.so.6()(64bit) libQt6Core.so.6()(64bit) libQt6Core.so.6(Qt_6)(64bit) libQt6Core.so.6(Qt_6.5)(64bit) libQt6DBus.so.6()(64bit) libQt6DBus.so.6(Qt_6)(64bit) libQt6Gui.so.6()(64bit) libQt6Gui.so.6(Qt_6)(64bit) libQt6Quick.so.6()(64bit) libQt6Quick.so.6(Qt_6)(64bit) libQt6Widgets.so.6()(64bit) libQt6Widgets.so.6(Qt_6)(64bit) libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.32)(64bit) libc.so.6(GLIBC_2.34)(64bit) libc.so.6(GLIBC_2.4)(64bit) libkdecorations2.so.5()(64bit) liblightlycommon6.so.5()(64bit) libm.so.6()(64bit) libm.so.6(GLIBC_2.2.5)(64bit) libstdc++.so.6()(64bit) libstdc++.so.6(CXXABI_1.3)(64bit) libstdc++.so.6(CXXABI_1.3.9)(64bit) libstdc++.so.6(GLIBCXX_3.4)(64bit) libstdc++.so.6(GLIBCXX_3.4.30)(64bit) rtld(GNU_HASH)
Checking for unpackaged file(s): /usr/lib/rpm/check-files /builddir/build/BUILDROOT/lightly-1.0.0-2.fc39.x86_64

Wrote: /builddir/build/RPMS/lightly-1.0.0-2.fc39.x86_64.rpm

Now  i have  to test it  with plasma6  and hope to have  no issues..

**Comment by alba4k** [comment]
@Kara-Zor-El I have tried compiling and installing your fork (using the instructions in the aur pkgbuild) but Lightly does not seem to show up as an option in qt6ct..

**Comment by edpil02** [comment]
My   Qt6  port   of lightly   seems to work  with  alpha version  of  plasma 6
![Screenshot_20230919_104008](https://github.com/Luwx/Lightly/assets/43163048/14dc9d2f-081f-49c1-8ee9-216c495ecfe3)

**Comment by alba4k** [comment]
Mind explaining how to get this working (with qt6ct)? :P

**Comment by mak448a** [comment]
@edpil02 Can you share the source code?

**Comment by dhruv8sh** [comment]
Updates on this?

**Comment by boehs** [comment]
x-post from boehs/Lightly, but would people be interested on placing a bounty on this feature?

**Comment by alba4k** [comment]
https://github.com/boehs/Lightly/issues/13
