### ISSUE TITLE
Transparency issue

### ISSUE THREAD

**Issue by SkeJm** [Luwx/Lightly#221]
Using hyprland with archlinux.
As you can see on the screenshot there is a little bit of my actual wallpaper without any blur and the gray box is actually a default Hyprland wallpaper.
How to make it to be transparent and show actual wallpaper?

![2023-12-08-183057_hyprshot](https://github.com/Luwx/Lightly/assets/36744236/86730afc-89cb-4852-915f-bc5c2af74974)

**Comment by Spatchy** [comment]
@SkeJm Did you find a way to adjust/disable the transparency on Hyprland? The readme only has instructions for Plasma

**Comment by TKK13909** [comment]
Hey, this repo has been abandoned. https://github.com/Bali10050/Lightly is being actively maintained so you should probably give it a try and see if your issue still occurs.

**Comment by SkeJm** [comment]
> @SkeJm Did you find a way to adjust/disable the transparency on Hyprland? The readme only has instructions for Plasma

> Hey, this repo has been abandoned. https://github.com/Bali10050/Lightly is being actively maintained so you should probably give it a try and see if your issue still occurs.

I've managed to fix it, but I forgot how tbh, sorry for late response lol
