### ISSUE TITLE
Window Decoation: rounded corners broken

### ISSUE THREAD

**Issue by tfl** [Luwx/Lightly#23]
Rounded borders are round only above light background. If there is a dark background behind the window title bar, rounded corners are gone.
![Screenshot_20200924_072349](https://user-images.githubusercontent.com/228038/94104420-4d31ff00-fe37-11ea-97e1-fbc95d78c0e0.png)

I like Lightly especially over Breeze Window decoration because it draws a nice shiny line at the top of the title bar which makes the window more distinguishable from other windows in dark themes.

**Comment by tfl** [comment]
OK, there is a workaround documented here: https://bugs.kde.org/show_bug.cgi?id=395725. Disable the Blur effect (or Verwischen in german). I do not care about this effect so disabling this is OK for me. I close this issue as it seems it has nothing to do with the theme itself but with Plasma

**Comment by Luwx** [comment]
Another workaround is to set the ```"blur"``` to false in this file https://github.com/Luwx/Lightly/blob/master/kdecoration/lightly.json before compiling the code.

This only happens in the decoration, for the rest of the window Lightly correctly calculates the blur region 
![2020-09-23_21-29](https://user-images.githubusercontent.com/33076480/94115467-24ead600-fe20-11ea-8db8-334282074c81.png)

**Comment by alxlg** [comment]
@tfl [comment number 16](https://bugs.kde.org/show_bug.cgi?id=395725#c16) in that bug report says that non-Aurorae themes, for examples forks of Breeze like the one by Lightly, can fix the issue for themselves, so I think this ticket is still valid.

**Comment by tfl** [comment]
Well, I think @Luwx is free to decide otherwise.

**Comment by tfl** [comment]
However, I may append this: setting `blur: false` did not solve the problem. I had to disable the blur effect entirely.

**Comment by Luwx** [comment]
> @tfl [comment number 16](https://bugs.kde.org/show_bug.cgi?id=395725#c16) in that bug report says that non-Aurorae themes, for examples forks of Breeze like the one by Lightly, can fix the issue for themselves, so I think this ticket is still valid.

This doesn't happen in breeze because it sets ```"blur"``` to false by default. Unfortunately the decoration cannot control the blur area so there is not much I can do.

@tfl You may have to restart Kwin for this change to take effect.

**Comment by Zzombiee2361** [comment]
> Another workaround is to set the "blur" to false in this file https://github.com/Luwx/Lightly/blob/master/kdecoration/lightly.json before compiling the code.

@Luwx can you add this as an option on lightly window decoration settings?

**Comment by tfl** [comment]
> @tfl You may have to restart Kwin for this change to take effect.

Thanks. That indeed did help ;)

**Comment by tfl** [comment]
@Zzombiee2361 Maybe I can help with this a little bit. Helps to get into QT programming again after a long time

**Comment by tfl** [comment]
Well, I implemented the blur setting but I have no idea where to actually blur ;(
