### ISSUE TITLE
Translucency is broken after only one setting change

### ISSUE THREAD

**Issue by CavaleriOmar** [Luwx/Lightly#24]
After I wanted to make the side panel a little more transparent, it actually became completely opaque ... and any other changes didn't work.

I also deleted the configuration file in /home/.config

**Comment by Luwx** [comment]
Hmm I really cannot reproduce this, can you send a screenshot?

**Comment by CavaleriOmar** [comment]
The issue resolved itself after two reboots of the pc.

**Comment by AndydeCleyre** [comment]
I've never noticed transparent sidebar or transparent main view (if that's what's meant by "Transparent Dolphin view" in the settings) actually working.

![2020-10-23_22-02](https://user-images.githubusercontent.com/1787385/97065478-992dac00-157b-11eb-9d3b-8183d956ff47.png)

This is Arch Linux, with lightly `r2066.287151b6`.
