### ISSUE TITLE
tabs not rounded 

### ISSUE THREAD

**Issue by Da-Viper** [Luwx/Lightly#25]
the first tab is not rounded at the first corner 

![Screenshot_20200927_180441](https://user-images.githubusercontent.com/57949090/94371130-06206400-00ec-11eb-916c-ea40270c1938.png)

but the other are rounded 

![Screenshot_20200927_180213](https://user-images.githubusercontent.com/57949090/94371108-dd986a00-00eb-11eb-8b1a-a6324b764012.png)

the corner left of the general tab  (the first tab )

love the style btw !

**Comment by Luwx** [comment]
Yeah it's missing there.

**Comment by Luwx** [comment]
No longer valid with 23db28a87053b2cf7ec2eae3b11c70fe5fc0ff57
