### ISSUE TITLE
Way to re-enable floating tabs

### ISSUE THREAD

**Issue by StarrKiss** [Luwx/Lightly#27]
In older builds, we had floating tabs- now we have these weird ones that are attached to the frame. This is very much a preference thing, but I prefer the old tab system- it just looked much cleaner+less busy, ESPIECALLY with a dark color scheme where the new system looks muddy- 
![image](https://user-images.githubusercontent.com/13007697/94692555-45230500-02f8-11eb-822a-6fe00cbfe71f.png)
and hard to see.
Can there please be an option to enable floating tabs?

**Comment by ryu-ketsueki** [comment]
I agree. Not to mention that it is more friendly depending on the program. Kdenlive and Konsole, for example, could use an option for floating tabs

**Comment by Luwx** [comment]
Done in 23db28a87053b2cf7ec2eae3b11c70fe5fc0ff57 . 

No floating tabs for Konsole or any app that use "movable" tabs, though.
