### ISSUE TITLE
Ripple effect

### ISSUE THREAD

**Issue by Zzombiee2361** [Luwx/Lightly#29]
Would be cool to add ripple effect from material design to buttons.
 
![](https://i.redd.it/svjnifxz23r51.gif)

Related discussion: https://www.reddit.com/r/kde/comments/j4zakn/is_there_a_way_to_replicate_this_effect_in_kde/

**Comment by Luwx** [comment]
Looks really nice, I'll try to implement it, but animations in qt widgets style is really painful, so it might take a while.

**Comment by Luwx** [comment]
Done in dc12c3a1a703454c706760f02f39524edd002794!

![Peek 2021-02-05 21-59](https://user-images.githubusercontent.com/33076480/107103846-e74e7e80-67fd-11eb-9ded-073814dc92b9.gif)
(it's not this slow)

The ripple doesn't start from the mouse position though, I have to look that up later.

**Comment by Zzombiee2361** [comment]
Holy shit this is so cool! At least this works like ripple effect in gtk.
