### ISSUE TITLE
LibreOffice: Wrong Shadows with new UI (tabs)

### ISSUE THREAD

**Issue by BatmansGehilfe** [Luwx/Lightly#30]
When using lightly (lightly-git from AUR) with LibreOffice's new "Ribbon-UI", the tabs' shadowing looks off:

![Screenshot_20201005_155117](https://user-images.githubusercontent.com/5390202/95088350-1e633500-0723-11eb-9cd8-65f6ccbf146b.png)

Absolutely love the style BTW!

**Comment by Luwx** [comment]
Done in 23db28a87053b2cf7ec2eae3b11c70fe5fc0ff57 .
