### ISSUE TITLE
installation problem in debian

### ISSUE THREAD

**Issue by Gaw18** [Luwx/Lightly#31]
I don't know how to go ahead with the installation
I have Debian 10 
![Screenshot_20201020_014053](https://user-images.githubusercontent.com/61871789/96523590-5f585f00-1276-11eb-8d77-e591f12e824f.png)
![Screenshot_20201020_014125](https://user-images.githubusercontent.com/61871789/96523588-5d8e9b80-1276-11eb-84d4-5367021f381a.png)

**Comment by ThePythonicProgrammer** [comment]
I had the same problem on Debian 10 when I tried to run it. I upgraded to Sid (Unstable), and it runs like a charm. My guess is that the dependencies for Debian 10 are not at a high enough version for Lightly.

**Comment by Luwx** [comment]
Yeah, looks like it, the KWindowShadow was introduced in recent versions of Kwin.
