### ISSUE TITLE
Unable to make paddings smaller

### ISSUE THREAD

**Issue by atolstoy** [Luwx/Lightly#32]
Hello and thank you for the lovely Lightly Qt5 style! I really like it!
However, what I really suffer from is the huge spaces in menus as well as oversized buttons. I would like it to be configurable somewhere in the style settings. Is it possible to make those controls more compact, like in QtCurve or Skulpture?

**Comment by Luwx** [comment]
The reason paddings are so huge is to accomodate shadows in various elements. I don't know any other way to make "big" (6px or more) drop shadows. Making it configurable would increase the code complexity a lot.

**Comment by Luwx** [comment]
If you still want small paddings, you can change the value of `Frame_FrameWidth` in https://github.com/Luwx/Lightly/blob/master/kstyle/lightly.h before compilation. Shadows will be affected.

**Comment by atolstoy** [comment]
Thanks for making it clear! BTW, I wish we had a qt5 style with a compact layout, like [Skulpture](https://github.com/cfeck/skulpture/tree/five). So, maybe it's worth changing shadows to simpler outlines?

**Comment by atolstoy** [comment]
> 
> 
> If you still want small paddings, you can change the value of `Frame_FrameWidth` in https://github.com/Luwx/Lightly/blob/master/kstyle/lightly.h before compilation. Shadows will be affected.

Okay, I've made paddings smaller as you suggested, and now Lightly looks much better, to my taste. However, is there a way to disable icons on push buttons? I can't seem to find the proper setting...
