### ISSUE TITLE
KDE Store?

### ISSUE THREAD

**Issue by digitalethics** [Luwx/Lightly#33]
Would you consider making _Lightly_ available via the KDE Store so that it can be conveniently installed and updated via the system settings?

**Comment by Luwx** [comment]
Not possible to install and update it in the system settings as far as I know, but it is in the store: https://store.kde.org/p/1414190/

**Comment by digitalethics** [comment]
@Luwx Thanks for letting me know that it's actually in the store. I initially didn't find it as it is listed under _Application Styles_ rather than _Global Themes_. If you list it under the latter it should be possible to install it via the system settings and also gain more visibility.
