### ISSUE TITLE
Rounded bottom corners option not appearing

### ISSUE THREAD

**Issue by niviciuz** [Luwx/Lightly#34]
I'm using Arch Linux, a fresh install from few days ago. I installed the theme and everything works fine, except from the "Round bottom corners" option just not appearing in the settings window. i hope there's something I can do for enabling it?

![image](https://user-images.githubusercontent.com/70601118/99246564-69ca3200-27fd-11eb-92dd-24f6e416e3cf.png)

**Comment by luema** [comment]
I don't see the "Round bottom corners" option in my config either. I thought maybe the config window screenshot in the Readme was just from an older release, but it appears it's still there [in the most recent version](https://github.com/Luwx/Lightly/releases/tag/v0.3-alpha):

![](https://user-images.githubusercontent.com/33076480/92879576-86a04e80-f3e3-11ea-9740-ee1b91959ac9.png)

**Comment by Luwx** [comment]
The option was removed, I recommend using https://github.com/Luwx/LightlyShaders
