### ISSUE TITLE
Tabs look very weird in Konsole, on master

### ISSUE THREAD

**Issue by aleasto** [Luwx/Lightly#35]
There are some issues with tabs here and there, but i find Konsole to have the weirdest one:
![tab1](https://i.imgur.com/Sg3kCKz.png)
![tab2](https://i.imgur.com/oB12a7Q.png)
![tab3](https://i.imgur.com/48vlVmh.png)

**Comment by Luwx** [comment]
Yes, it looks weird on anything other than in the top. I'll have to rewrite the tab style again.

**Comment by Luwx** [comment]
Done in 23db28a87053b2cf7ec2eae3b11c70fe5fc0ff57 .
