### ISSUE TITLE
Broken UI in OBS Studio 

### ISSUE THREAD

**Issue by phrxmd** [Luwx/Lightly#38]
Lightly breaks the UI for OBS Studio (tried with OBS 26.1.0, Qt 5.15.2, KDE 5.20.4, Frameworks 5.76.0 on recent OpenSUSE TW).

The OBS main window has a sidebar-type area at the bottom where some tool windows can be docked. With Lightly, this area is filled with garbage from the windows below, see the video at https://www.youtube.com/watch?v=97noBvmWoMA. 
When I select Breeze theme instead of Lightly, the problem goes away, so the issue seems to be with the theme.

**Comment by miguelski** [comment]
i had the same problem, it seems is related to the transparency, i recall if you use a color scheme without transparency it works

**Comment by ryu-ketsueki** [comment]
Latest commit from Master, the issue still persists. Also openSUSE TW.
![Flameshot_20210123_010115](https://user-images.githubusercontent.com/39316730/105568693-3387c200-5d1a-11eb-8f36-7fc9ddb2cace.png)

**Comment by Luwx** [comment]
@ryu-ketsueki Should be fixed now. I accidentally added a space before the app name and it wasn't properly identified.

**Comment by ryu-ketsueki** [comment]
![image](https://user-images.githubusercontent.com/39316730/105575854-757e2b80-5d4d-11eb-8f12-7b5394a2d80b.png)
Now it is properly working on my end. For a moment I thought it was some sort of incompatibility with 5.21 Beta which, by the way, LightlyShaders fails to compile for. I'm gonna submit an issue there with all the details. Plasma 5.21 is just around the corner with this Beta, maybe we could get LightlyShaders working with it as well.
