### ISSUE TITLE
Upside down tabs are broken in Kdenlive

### ISSUE THREAD

**Issue by ludovitkramar** [Luwx/Lightly#40]
![Screenshot_20210104_121456](https://user-images.githubusercontent.com/61901244/103500603-76edbf80-4e43-11eb-93ce-ffb12bf8dce7.png)

**Comment by ludovitkramar** [comment]
r2066.287151b6-1 from AUR in arch linux

**Comment by 4VRDriver** [comment]
Duplicate of https://github.com/Luwx/Lightly/issues/35

**Comment by Luwx** [comment]
Done in 23db28a87053b2cf7ec2eae3b11c70fe5fc0ff57 .
