### ISSUE TITLE
The option to control the transparency of the titlebar does not seem to work

### ISSUE THREAD

**Issue by kupiqu** [Luwx/Lightly#46]
No matter the chosen option the transparency is fixed. I can adjust that of the sidebar but not that of the titlebar

**Comment by Luwx** [comment]
Are you changing the titlebar alpha value in the color scheme directly?

**Comment by kupiqu** [comment]
No, I just meant the following:

![image](https://user-images.githubusercontent.com/3875196/106798020-af103a00-665d-11eb-802b-c203b4e44178.png)

but it's silly, I just realized this is for the menus (which I don't have because I use globalmenu) instead of titlebar. I guess there is no way to  configure titlebar's alpha value from the same setting option.

feel free to close the issue.

**Comment by Luwx** [comment]
That option is actually for context menus :D
![image](https://user-images.githubusercontent.com/33076480/106808320-0061fe80-6649-11eb-8d92-766a113d0c5f.png)

The toolbar/menubar should remain using the titlebar color/opacity, if I add a opacity slider for them they will no longer follow the color scheme, and some applications can have different color schemes.
