### ISSUE TITLE
Hover effect missing on titlebar buttons in Firefox and Thunderbird

### ISSUE THREAD

**Issue by laubblaeser** [Luwx/Lightly#50]
Hovering over the close button (the circle with the X in it) should turn it red. This works perfectly fine in KDE apps (e.g. Dolphin or Kate) but the hover effect doesn't occur in Firefox and Thunderbird. Clicking on the button changes its colour as expected.

It's just a minor detail in the area of theme consistency but maybe it's fixable somehow?

**Comment by laubblaeser** [comment]
I just realised that I should maybe share some info on what I'm using: Lightly 0.4 (thanks for the update btw!) and Breeze GTK theme on a regular Manjaro KDE install (i.e. not on testing or unstable channel).

**Comment by Curve** [comment]
Those buttons are GTK buttons, Lightly is just a QT Theme thus it will not change them.
You may be interested in #51

**Comment by Luwx** [comment]
Breeze gtk issue.
