### ISSUE TITLE
No transparent sidebar

### ISSUE THREAD

**Issue by pooh2pooh** [Luwx/Lightly#52]
Hi! Cool Job!

No transparent Sidebar Dolphin :(
![Screenshot_20210207_165431](https://user-images.githubusercontent.com/21198356/107148642-6e6a3680-6965-11eb-828e-b23756e95ea4.png)

**Comment by TobiPeterG** [comment]
Works for me, did you select Lightly in Application Style tab in Plasma settings?

**Comment by pooh2pooh** [comment]
> Works for me, did you select Lightly in Application Style tab in Plasma settings?

![image](https://user-images.githubusercontent.com/21198356/107154080-05dd8280-6982-11eb-8eee-a083bebf8da3.png)

**Comment by Luwx** [comment]
Looks like you are using fractional display scaling, and Lightly doesn't support transparency with this, see https://github.com/Luwx/Lightly/issues/16
