### ISSUE TITLE
I would looove to see LIM (Locally Integrated Menu)

### ISSUE THREAD

**Issue by ranomier** [Luwx/Lightly#55]
![](https://camo.githubusercontent.com/8b8e47435fbd4ddf83829705de223353541255bb2884b778cfda877a1df4878b/68747470733a2f2f692e696d6775722e636f6d2f6f464f56576a562e706e67)
source: https://github.com/Zren/material-decoration

So basically what you see above.
❤❤❤

**Comment by Luwx** [comment]
Hmm.. the implementation is definitely not trivial :/

It would be better to wait for an upstream implementation https://bugs.kde.org/show_bug.cgi?id=375951,
