### ISSUE TITLE
Center aligned tabs

### ISSUE THREAD

**Issue by D3SOX** [Luwx/Lightly#58]
Just like in Kvantum
![2021-02-07_17-29](https://user-images.githubusercontent.com/24937357/107152795-31547300-696a-11eb-8118-307ff1f36d86.png)

**Comment by Luwx** [comment]
?
Tabs (non editable ones) are already center aligned.

**Comment by D3SOX** [comment]
No, you can even see this in the Screenshot in the readme (Lightly-default.png)
Tabs in Dolphin are left-aligned

**Comment by Luwx** [comment]
Ah, right, you are referring to the editable ones. You can add this line to the lightlyrc file under the `[Style]` section: `TabBarDrawCenteredTabs=true`

![image](https://user-images.githubusercontent.com/33076480/108282873-1e5b5300-7161-11eb-8f2e-4aaa7eec5231.png)

**Comment by D3SOX** [comment]
Nice but wouldn't it be better if there was an option for this in Plasma style's settings?

**Comment by Luwx** [comment]
I was planning to remove this option altogether but I'll reconsider.
