### ISSUE TITLE
is there any place to disable the blur ? 

### ISSUE THREAD

**Issue by Da-Viper** [Luwx/Lightly#6]
because currently it does not blur it just becomes transparent if you put the tool bar on the side ?

**Comment by Luwx** [comment]
Right now you have to resize the window to update the blur effect. 

I've added an option to configure the transparency in the settings page:
![image](https://user-images.githubusercontent.com/33076480/90579214-b7ea7d80-e19b-11ea-90e2-3ae15a19d2cc.png)

When it's 100% opaque there is no blur. Can you test if anything crash if you apply the setting?
