### ISSUE TITLE
Does the AUR package receive any updates?

### ISSUE THREAD

**Issue by maeckha** [Luwx/Lightly#60]
Since the 3rd of August there weren´t any updates to this package ( https://aur.archlinux.org/packages/lightly-git ). So would it be advisable to install it nonetheless?

**Comment by Curve** [comment]
Its a git package, if you look at the PKGBUILD you will see that it just clones this repo and builds it.
There's rarely need for updates in git packages, it will probably work fine and you can install it

**Comment by maeckha** [comment]
Thanks!
