### ISSUE TITLE
[Feature Request] Hide the scrollbar after scrolling 

### ISSUE THREAD

**Issue by Da-Viper** [Luwx/Lightly#61]
The scrollbar  could be hidden and only shown when the mouse moves or and it get a little bigger when it is hovered upon,
why you may ask ? , it makes the application look more nice aesthetically,  and adds the extra room gained from hiding it.

It is also how it is done on Gnome, Windows and Mac, and i like it also, could you please add it thanks.

**Comment by Curve** [comment]
Related #53

**Comment by Luwx** [comment]
Duplicated.
