### ISSUE TITLE
Dolphin full transparency

### ISSUE THREAD

**Issue by brighton64** [Luwx/Lightly#62]
How can I make all of dolphin transparent? So far I have been able to make the side bar and titlebar transparent by adding a fourth value to `inactiveBackground activeBackground` in color scheme file under section `WM`. 
But how can I make the rest of dolphin transparent?

**Comment by Luwx** [comment]
See https://github.com/Luwx/Lightly/discussions/43#discussioncomment-322880

I must say that currently this option is experimental and has some problems.
