### ISSUE TITLE
Menu selection repainting is lagging

### ISSUE THREAD

**Issue by szotsaki** [Luwx/Lightly#64]
When hovering the mouse to the next menu item the selection rectangle is moving slower than the mouse and this way it feels laggy.

It can be demonstrated when the mouse is moved quickly over the menu items; in that case the selection repaint is done halfway only.

An APNG animation showing the issue in Dolphin: https://mega.nz/file/0MACkLAD#vnfAno2KjyprzILix4HVgUKch_iRhM_BkpIo3iUVVHU

**Comment by Luwx** [comment]
I could not play the animation. And looks like you are using an old version of Lightly, can you test with the latest?

**Comment by Luwx** [comment]
Possibly invalid.
