### ISSUE TITLE
Dependencies for Solus KDE

### ISSUE THREAD

**Issue by hummblebee** [Luwx/Lightly#66]
I successfully installed Lightly and all the dependencies (including the optionals) on Solus and would appreciate if these were added to README:
```
sudo eopkg install extra-cmake-modules kdecoration-devel qt5-declarative-devel qt5-x11extras-devel qt5-base-devel kcoreaddons-devel kguiaddons-devel kconfigwidgets-devel kwindowsystem-devel ki18n-devel kiconthemes-devel kcmutils-devel libxcb-devel xcb-util-devel qt5-wayland-devel kwayland-devel wayland-devel frameworkintegration-devel

```

**Comment by Luwx** [comment]
Can you post the output of the command `kcmshell5 lightlydecorationconfig` ?

**Comment by Luwx** [comment]
I'll update the README

**Comment by hummblebee** [comment]
@Luwx Thanks for the reply, I removed the Lightly directory and re-did all the steps and the issue is resolved, seems like all the dependency searching and running CMake in between messed up the configurations somehow!

Only one thing, there's no "Lightly" theme in Global sections and there's only one in "Application Styles" and "Window Decorations" is this the intended behavior or am I missing something?

**Comment by Luwx** [comment]
That's because there is no Lightly global theme yet. Once the plasma theme is done I'll maybe create one.

**Comment by hummblebee** [comment]
Thank you, I just thought I missed something during the build process. If you needed testing or anything on Solus, I'd be happy to help. Kudos and good luck. 😉

**Comment by hummblebee** [comment]
I believe I missed one key package in my previous comment, `system.devel` that contains build binaries such as `make`, `cmake` and etc... for which the command syntax differs a bit as the following:

```
sudo eopkg install -c system.devel
```

**Comment by thomhoess** [comment]
Please update the README, there's still no hint that you need to install system.devel, thankfully found this issue to find out what was missing. Thanks!
