### ISSUE TITLE
Enhance tabs layout

### ISSUE THREAD

**Issue by Leinatan** [Luwx/Lightly#67]
First of all, thank you so much for this project. It's almost weird but since I've installed Lightly (along with Lüv icon theme) I just love to simply open Dolphin and be amazed at it haha.

However incredible your theming is, tabs still have some little weird "issues".
![image](https://user-images.githubusercontent.com/21956401/107760228-b56f7780-6d29-11eb-9d55-8f416912b6a4.png)

In this screenshot I tried to show how the left pane, the toolbar and the tabs bar interact weirdly with residual space between each other. Feels a bit off. 

1. I think that the left panel and the main view should have their top at the exact same height, rather than having 1 px difference. i don't know if it's a feature or a bug though.

2. There should be no gap between the first tab and the left side of the main view.

**Comment by Luwx** [comment]
Thanks for the feedback!
 >I think that the left panel and the main view should have their top at the exact same height, rather than having 1 px difference. i don't know if it's a feature or a bug though.

They are at the same height, it's the shadow pointing to different directions that gives this weird impression.

>There should be no gap between the first tab and the left side of the main view.

Yeah, I'm still trying to find out where was this gap introduced.
