### ISSUE TITLE
Translucency is disabled on HiDPI displays when scaling is 125%.

### ISSUE THREAD

**Issue by edfloreshz** [Luwx/Lightly#70]
After toggling 125% scaling in Plasma, all translucency effects were disabled except window title bars.

**Comment by Luwx** [comment]
Please see https://github.com/Luwx/Lightly/issues/16
Translucency is disabled for non integer scaling factors.

**Comment by Dynakarp** [comment]
Hello, it appears 39700ce is no longer necessary, with QT 5.15 at the very least, it looks fine at 175% scaling with 39700ce reverted.
![Screenshot_20210426_193404](https://user-images.githubusercontent.com/69023488/116167725-72853500-a6c6-11eb-90d3-0e20324742e2.png)

**Comment by edfloreshz** [comment]
Awesome! Thanks for letting us know.
