### ISSUE TITLE
"Configure Netspeed Widget..." crashes Plasmashell

### ISSUE THREAD

**Issue by owlbrick** [Luwx/Lightly#71]
Trying to open "Configure Netspeed Widget..." (right-clicking on the Netspeed widged on the panel) crashes Plasmashell.

KDE Plasma Version: 5.21.80
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2

This is the output I get launching plasmashell from terminal ("kquitapp5 plasmashell && kstart5 plasmashell") when the fault is excited:

QQmlEngine::setContextForObject(): Object already has a QQmlContext
QQmlEngine::setContextForObject(): Object already has a QQmlContext
file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/ConfigurationAppletPage.qml:44:5: QML Loader: Binding loop detected for property "height"
KCrash: Attempting to start /usr/bin/plasmashell
KCrash: crashing... crashRecursionCounter = 2
KCrash: Application Name = plasmashell path = /usr/bin pid = 23368
KCrash: Arguments: /usr/bin/plasmashell

**Comment by Luwx** [comment]
I cannot reproduce the crash, but I'm not using Plasma 5.21 yet.

**Comment by LiveLM** [comment]
Can reproduce the crash on Plasma 5.21, same console output as OP.

**Comment by Zzombiee2361** [comment]
Could not reproduce with Plasma 5.21. Could this be the same issue as #63? If so try pulling updates and recompile lightly

**Comment by LiveLM** [comment]
Compiling the latest version seems to have fixed the issue.
