### ISSUE TITLE
Titlebar-window separator?

### ISSUE THREAD

**Issue by CavaleriOmar** [Luwx/Lightly#72]
How can I set Lightly to have the same separation between toolbar and window content as seen in the screenshots?

[https://github.com/Luwx/Lightly/blob/master/Lightly-custom.png](https://github.com/Luwx/Lightly/blob/master/Lightly-custom.png)

**Comment by Luwx** [comment]
This separator is automatically drawn when the titlebar color have transparency, like the Lightly color scheme.
