### ISSUE TITLE
Some Qt windows are translucent when using transparent headers

### ISSUE THREAD

**Issue by Reiddragon** [Luwx/Lightly#74]
Observed it with mGBA, possibly other applications too
![image](https://user-images.githubusercontent.com/40322297/108238540-b9e4c780-7151-11eb-9e74-0813123b1132.png)
The colorscheme being used is BreezeDracula with the transparency values set to 200, using any colorscheme without transparency values doesn't have this issue

**Comment by Luwx** [comment]
Some applications really don't work well with translucency effects. I don't know if this is the case with this one, but you can set it opaque in the lightlyrc (located ~/.config), under the [Style] section, adding the entry `OpaqueApps=appName1,appName2...`
