### ISSUE TITLE
Titlebar transparency is not visible on Plasma 5.21

### ISSUE THREAD

**Issue by AryToNeX** [Luwx/Lightly#75]
As the title says, updating to Plasma 5.21 makes the titlebars lose transparency, therefore the theme will look inconsistent.

![image](https://user-images.githubusercontent.com/13177694/108246633-f284a100-7151-11eb-894c-dd4186a28cb0.png)

Using Lightly 0.4 from AUR

**Comment by allaeddineomc** [comment]
just reload the colors and you will be ok
worked for me on arch plasma 5.21

**Comment by AryToNeX** [comment]
ok I must say that I am dumb
