### ISSUE TITLE
Dropdown menu on global menu is misaligned when using Latte dock

### ISSUE THREAD

**Issue by kgorol** [Luwx/Lightly#80]
Operating System: Manjaro
KDE Plasma Version: 5.20.5
Graphics Platform: X11
Dock: Latte

<img width="303" alt="image" src="https://user-images.githubusercontent.com/34159482/109106824-e2138e00-7730-11eb-8401-b92838336609.png">

**Comment by ryu-ketsueki** [comment]
Can you verify if the same happens with different fonts and Plasma Themes? Latte takes all that into account. Also, I noticed you have a dock on the left side of the screen. If I compare with my own configuration, which is with Latte, Breeze AlphaBlack, Lucida Sans font, both Lightly and LightlyShaders and no dock on the left, it is not misaligned.
![image](https://user-images.githubusercontent.com/39316730/109180112-50744280-7769-11eb-9f9f-2e4428852984.png)

**Comment by kgorol** [comment]
Well, I guess I have not noticed it before :) It must be something related to the Latte Dock then, not this theme.

**Comment by Luwx** [comment]
There is very little the style can do to control the positioning of the context menu, so this must be caused by other factors. Feel free to reopen this issue if the problem happens only with Lightly.
