### ISSUE TITLE
Okular toolbar is transparent but not blurred

### ISSUE THREAD

**Issue by aleasto** [Luwx/Lightly#81]

**Comment by LiveLM** [comment]
Can confirm I also have this issue, not only on Okular but also on the config window of Syncthing Tray.
![Screenshot_20210225_101758](https://user-images.githubusercontent.com/34987841/109158952-f32dc080-776b-11eb-851d-79235e25bfed.png)
![Screenshot_20210225_101052](https://user-images.githubusercontent.com/34987841/109158811-c679a900-776b-11eb-86a8-a31f4311407c.png)

I'm using:
The latest version of Lightly (just compiled it)
KDE Plasma Version: 5.21.1
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2

**Comment by LiveLM** [comment]
Can confirm I also have this issue, not only on Okular, but also on the config window of Syncthing Tray.
![Screenshot_20210225_101758](https://user-images.githubusercontent.com/34987841/109159957-1efd7600-776d-11eb-9630-bf2a7d53f0a1.png)
![Screenshot_20210225_102530](https://user-images.githubusercontent.com/34987841/109159809-f6757c00-776c-11eb-8531-e5f3060f59a3.png)

I'm using:
The latest version of Lightly (just compiled it)
KDE Plasma Version: 5.21.1
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2

**Comment by Willem3141** [comment]
I'm having the same problem with Okular, and also with Kontact:  

![image](https://user-images.githubusercontent.com/7533280/109332754-d920da80-785e-11eb-8494-84681401dbf7.png)

**Comment by Luwx** [comment]
@LiveLM There is something very weird going on with this syncthing window, I tested with Kvantum and it does the same thing. You can either add the window to the opaque list or choose a different style for it in its "Qt" settings page.

**Comment by LiveLM** [comment]
> You can either add the window to the opaque list

The opaque list? Where would one find that?

**Comment by Luwx** [comment]
@LiveLM I explained here https://github.com/Luwx/Lightly/issues/74#issuecomment-780914501

I'll add this setting to the config page so that it's easier.

**Comment by LiveLM** [comment]
Having this setting on the config page will be really helpful, thanks!
