### ISSUE TITLE
Support for new header?

### ISSUE THREAD

**Issue by ryu-ketsueki** [Luwx/Lightly#82]
Plasma is overhauling their visuals slowly but the new applications already reflect the changes, like Neochat and Discover. Other ones like Dolphin and Kate, which still use toolbars, show the transparency as intended. What can be done to make the headers for those applications behave similarly to the toolbars?
![image](https://user-images.githubusercontent.com/39316730/109178189-5d903200-7767-11eb-8e4c-daa49414c764.png)
![image](https://user-images.githubusercontent.com/39316730/109178419-992afc00-7767-11eb-99a5-6e09e8f03ae5.png)

**Comment by DiegoMagdaleno** [comment]
Off topic question but how did you get tags there?

**Comment by D3SOX** [comment]
Also off topic: How did you get the top panel completely transparent and does it get opaque when maximizing a window?

**Comment by Luwx** [comment]
It's not possible to have translucency forced from the style with Kde QML applications, unfortunately.
