### ISSUE TITLE
Window buttons

### ISSUE THREAD

**Issue by leoneivaw** [Luwx/Lightly#85]
How to change the window buttons(close, minimize, maximize).
Despite of this great theme i hate Breeze default theme buttons.
I love the plastik buttons.
Thanks!

![image](https://user-images.githubusercontent.com/58883997/109698320-0e367100-7b6e-11eb-866c-6a98a3516063.png)

**Comment by Taza53** [comment]
![image](https://user-images.githubusercontent.com/34032665/111923462-a1910100-8a9f-11eb-84b2-9b01f06b6a8d.png)
you can change it in window decorations. and a good place to ask questions for [kde](https://www.reddit.com/r/kde/) and this one is for [linux](https://www.reddit.com/r/linuxquestions).

**Comment by Luwx** [comment]
I recommend https://github.com/paulmcauley/classikstyles for more button styles.
