### ISSUE TITLE
Kaffeine video frame is semitransparent when using Lightly

### ISSUE THREAD

**Issue by RizzoV** [Luwx/Lightly#88]
Debian Bullseye/11 (sid)
KDE Plasma: 5.20.5
KDE Frameworks: 5.78.0
Qt: 5.15.2
Lightly: 0.4.1

![b](https://user-images.githubusercontent.com/12030659/110221690-fd6b5f80-7ecd-11eb-938b-97e03f452e0b.png)

As the screenshot shows, Kaffeine presents a semitransparent video frame when using Lightly (the plants picture is my wallpaper). It does not do so when using any other application style.

A temporary workaround I found is to select another application style, open Kaffeine and then re-apply Lightly. In this way, Kaffeine's UI will be updated to Lightly's style but the video frame will maintain its opacity.

**Comment by Luwx** [comment]
Looks like Kaffeine is not compatible with transparency.
