### ISSUE TITLE
Square version

### ISSUE THREAD

**Issue by Niwton** [Luwx/Lightly#9]
Is it possible to leave everything square instead of everything round? on low resolution monitors rounded corners get pixel error.

**Comment by Luwx** [comment]
I plan to add a "roundness" setting in the future. It shouldn't be too hard.

> rounded corners get pixel error

Can you send a screenshot?

**Comment by Niwton** [comment]
able to compile a version with square corners was very beautiful

![Screenshot_20200903_172102](https://user-images.githubusercontent.com/24793957/92186568-9214d800-ee2d-11ea-907c-5f139ac6061a.png)
![Screenshot_20200903_172008](https://user-images.githubusercontent.com/24793957/92186567-90e3ab00-ee2d-11ea-9d3d-6c35142a11bb.png)

**Comment by nnamliehbes** [comment]
Looks great! To avoid this blur-bug on rounded corners I would like to recompile Lightly on my own to make everything square. Do you have any hints for me which keywords I have to look out for in the files?

**Comment by mmetak** [comment]
> Looks great! To avoid this blur-bug on rounded corners I would like to recompile Lightly on my own to make everything square. Do you have any hints for me which keywords I have to look out for in the files?

You should change the radius value `Frame_FrameRadius,` in these two files:
`kstyle/lightly.h` & `kdecoration/lightly.h`

**Comment by Niwton** [comment]
> > Looks great! To avoid this blur-bug on rounded corners I would like to recompile Lightly on my own to make everything square. Do you have any hints for me which keywords I have to look out for in the files?
> 
> You should change the radius value `Frame_FrameRadius,` in these two files:
> `kstyle/lightly.h` & `kdecoration/lightly.h`

Exactly, and very simple.

**Comment by Niwton** [comment]
With the square corners it reduced the bugs a lot, only in the tabs that still remains a stranger

**Comment by nnamliehbes** [comment]
> > Looks great! To avoid this blur-bug on rounded corners I would like to recompile Lightly on my own to make everything square. Do you have any hints for me which keywords I have to look out for in the files?
> 
> You should change the radius value `Frame_FrameRadius,` in these two files:
> `kstyle/lightly.h` & `kdecoration/lightly.h`

Worked like a charm! Thank you!

**Comment by Luwx** [comment]
Corner radius is now configurable!

![2020-09-10_21-33](https://user-images.githubusercontent.com/33076480/92832083-956c0e80-f3ad-11ea-8add-33d484cc4ef8.png)

It's limited at 8 pixels, any more than this may cause some glitches.
