### ISSUE TITLE
Does transparency only work with Lightly as a window decoration?

### ISSUE THREAD

**Issue by CavaleriOmar** [Luwx/Lightly#94]
But the transparency of the toolbar, does it activate only using Lightly or also with other window decorations that have transparency?

For example, in the attachment I use Breeze-Blurred, but the toolbar remains opaque.
[https://i.imgur.com/raIIJ1I.png](url)

**Comment by ewertonl** [comment]
It works fine, sometimes. Like you can see in the screenshot:
![image](https://user-images.githubusercontent.com/79954630/113072130-af7c0b80-919c-11eb-903f-90d4d357cbf0.png)

The background colors in your colorscheme needs to have some alpha value below 255 in the `[Colors:Window]` section:
![image](https://user-images.githubusercontent.com/79954630/113072319-287b6300-919d-11eb-8e0b-8444c75a8211.png)

**Comment by ewertonl** [comment]
breeze blurred is just the window decorations. the toolbar is the application style, breeze does not blur window elements with colorschemes. you can customize some kvantum theme's svgs to get blur in the kvantum application style.

**Comment by ryu-ketsueki** [comment]
Actually you can make elements transparent on Lightly. The way it is done is a bit of a workaround, though. You need to edit the color scheme file directly and add the Alpha value. For example, the color for the active background of the titlebar is 245,245,245,220. It will set the titlebar transparent by a small bit and Lightly knows how to interpet that alpha value to set the toolbar the same transparency. It is when both the titlebar and toolbar are set to transparent and blurred. From my experience, only Lightly allows you to blur the toolbar like this. On Kvantum, you could blur the window itself but not only the toolbar.
