### ISSUE TITLE
v0.4.1: Elements are not really inside of frames (Screenshot).

### ISSUE THREAD

**Issue by antsn** [Luwx/Lightly#95]
I'm new to Lightly, and I disable all transparent effects.
Overall, I like Lightly except for how it renders windows scrolling frame box (sorry if I name it wrong).
Here are screenshots with dark and light theme enabled:
![Screenshot_20210328_082306](https://user-images.githubusercontent.com/22258109/112740060-d28f9b00-8fa3-11eb-920d-d27c7b84b1b6.png)
![Screenshot_20210328_082625](https://user-images.githubusercontent.com/22258109/112740063-d7ece580-8fa3-11eb-9d64-c8cd83f8ccb2.png)
![Screenshot_20210328_082642](https://user-images.githubusercontent.com/22258109/112740065-da4f3f80-8fa3-11eb-8772-f45103a724d7.png)

**Comment by Luwx** [comment]
This is a problem related to KDE qqc2-desktop-style. There is not much I can do.
