### ISSUE TITLE
color scheme used in screenshot in readme

### ISSUE THREAD

**Issue by BlitW0** [Luwx/Lightly#96]
What is the color scheme used here?

![](https://raw.githubusercontent.com/Luwx/Lightly/master/Lightly-fullglass.png)

**Comment by ewertonl** [comment]
I guess is ***Hello Dark*** from **[Hello Project](https://github.com/n4n0GH/hello)**
But probably with lowered alpha.
![Hello Color Schemes](https://github.com/n4n0GH/hello/raw/master/color-scheme/preview.png)

**Comment by qawsedrftgzh** [comment]
How do you lower the alpha?

**Comment by ArtyIF** [comment]
> How do you lower the alpha?

You need to find the color scheme file and edit it manually. IIRC you just add a fourth number to the needed color value.
