### ISSUE TITLE
Kate background broken

### ISSUE THREAD

**Issue by m4cri** [Luwx/Lightly#99]
The left and bottom menus in Kate are transparent. 
![Screenshot_20210409_081829](https://user-images.githubusercontent.com/62558399/114137351-59ca0080-990c-11eb-96e9-81ebcd02297f.png)

**Comment by edpil02** [comment]
Seems not related to Lightly 
Installed :
kwin-effect-LightlyShaders.x86_64     0.1-1.fc35   @@commandline  (git build)
Cause  I have no issue with kate.

![kate](https://user-images.githubusercontent.com/43163048/114172100-847c7f00-9935-11eb-9cbb-e7af3beddc95.png)

**Comment by edpil02** [comment]
Sorry iI made  a mistake : 
plasma-style-Lightly.x86_64    0.4.1-2.fc35     @@commandline (git build)

**Comment by m4cri** [comment]
Ok so i discovered that adding kate to the opaque list fixes it.
